name: 'Produce Presentation Content'
on:
  push:
    branches:
      - main
jobs:
  build-pptx:
    name: 'Build PowerPoint Presentation'
    runs-on: ubuntu-latest
    container:
      image: seesharprun/pandoc-build
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v2
      - name: 'Run Pandoc Builds'
        run: |
          echo "${{ github.sha }}" > v${{ github.run_number }}.rel.txt
          echo "github.run_number: v${{ github.run_number }}.rel.txt github.ref: ${{ github.ref }}" >> v${{ github.run_number }}.rel.txt
          echo "github.action: ${{ github.action }}" >> v${{ github.run_number }}.rel.txt
          echo "github.action_path: ${{ github.action_path }}" >> v${{ github.run_number }}.rel.txt
          echo "github.base_ref: ${{ github.base_ref }}" >> v${{ github.run_number }}.rel.txt
          echo "github.event: ${{ github.event }}" >> v${{ github.run_number }}.rel.txt
          echo "github.event_name: ${{ github.event_name }}" >> v${{ github.run_number }}.rel.txt
          echo "github.event_path: ${{ github.event_path }}" >> v${{ github.run_number }}.rel.txt
          echo "github.head_ref: ${{ github.head_ref }}" >> v${{ github.run_number }}.rel.txt
          echo "github.job: ${{ github.job }}" >> v${{ github.run_number }}.rel.txt
          echo "github.ref: ${{ github.ref }}" >> v${{ github.run_number }}.rel.txt
          echo "github.repository_owner: ${{ github.repository_owner }}" >> v${{ github.run_number }}.rel.txt
          echo "github.run_id: ${{ github.run_id }}" >> v${{ github.run_number }}.rel.txt
          echo "github.run_number: ${{ github.run_number }}" >> v${{ github.run_number }}.rel.txt
          echo "github.sha: ${{ github.sha }}" >> v${{ github.run_number }}.rel.txt
          echo "github.token: ${{ github.token }}" >> v${{ github.run_number }}.rel.txt
          echo "github.workflow: ${{ github.workflow }}" >> v${{ github.run_number }}.rel.txt
          echo "github.workspace: ${{ github.workspace }}" >> v${{ github.run_number }}.rel.txt
          ./test.sh "hello world v${{ github.run_number }}" >> v${{ github.run_number }}.rel.txt
          touch v${{ github.run_number }}.rel.txt
        working-directory: ./
      - name: 'Upload Presentation Artifacts'
        uses: actions/upload-artifact@v2
        with:
          name: presentations
          path: ./*.rel.txt
  release-content:
    name: 'Create GitHub Release'
    runs-on: ubuntu-latest
    needs: [ build-pptx ]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: 'Download Presentation Artifacts'
        uses: actions/download-artifact@v2
        with:
          name: presentations
      - name: 'Create GitHub Release'
        uses: softprops/action-gh-release@v1
        with:
          files: ./**/*.rel.txt
          tag_name: v${{ github.run_number }}
          name: Release V${{ github.run_number }}
